"""Update table

Revision ID: 059bd5cbbdab
Revises: e711663eb8c0
Create Date: 2022-12-21 12:50:10.904962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059bd5cbbdab'
down_revision = 'e711663eb8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('total_like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'total_like')
    # ### end Alembic commands ###
