"""Updated table

Revision ID: 483cb1672e37
Revises: 50dfcaaeb83d
Create Date: 2023-01-06 11:57:13.167733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "483cb1672e37"
down_revision = "50dfcaaeb83d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
