"""Updated post tabe

Revision ID: 925d31dc449b
Revises: 1f4dce620290
Create Date: 2022-12-26 17:43:46.122881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925d31dc449b'
down_revision = '1f4dce620290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_type')
    # ### end Alembic commands ###
