"""Created table

Revision ID: cfd32d5d0a79
Revises: 253eac7ad093
Create Date: 2023-01-06 10:27:00.395873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cfd32d5d0a79"
down_revision = "253eac7ad093"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "updated_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column("updated_by", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
